# Generated by Django 5.0.3 on 2024-03-28 18:17

import django.utils.timezone
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('image', models.ImageField(upload_to=home.models.wrapper)),
                ('Event_Start_Date', models.DateField(default=django.utils.timezone.now)),
                ('Event_End_Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
