# Generated by Django 5.0.3 on 2024-03-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
