# Generated by Django 5.0.3 on 2024-03-28 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=250)),
                ('subject', models.TextField(max_length=250)),
                ('created_at', models.DateField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
